all:
	g++ -ldl -pthread -O3 -std=c++2a main.cpp character-level-language-model.h -o ml; 
debug:
	g++ -ldl -pthread -g -std=c++2a main.cpp character-level-language-model.h -o ml_debug;
clean:
	rm -f ml ml_debug; clear	
